In [5]:
import numpy as np

In [ ]:
#FONTOS!!!

# CSAK OTT LEHET HASZNÁLNI FOR LOOP-OT AHOL A FELADAT KÜLÖN KÉRI!
# [1,2,3,4] --> ezek az értékek np.array-ek. Ahol listát kérek paraméterként ott külön ki fogom emelni!
# Ha végeztél a feladatokkal, akkor notebook-ot alakítsd át .py.
# A FÁJLBAN CSAK A FÜGGVÉNYEK LEGYENEK! (KOMMENTEK MARADHATNAK)

In [ ]:
# Írj egy olyan fügvényt, ami megfordítja egy 2d array oszlopait. Bemenetként egy array-t vár.
# Be: [[1,2],[3,4]]
# Ki: [[2,1],[4,3]]
# column_swap()

In [16]:
def column_swap(arr : np.array) -> np.array:
    return np.array(arr)[:,::-1]
#print(column_swap([[1,2],[3,4]]))

[[2 1]
 [4 3]]


In [ ]:
# Készíts egy olyan függvényt ami összehasonlít két array-t és adjon vissza egy array-ben, hogy hol egyenlőek 
# Pl Be: [7,8,9], [9,8,7] 
# Ki: [1]
# compare_two_array()
# egyenlő elemszámúakra kell csak hogy működjön

In [10]:
def compare_two_array(arr1 : np.array,arr2 : np.array) -> np.array:
    return np.flatnonzero(np.equal(np.array(arr1),np.array(arr2)).astype(int))

[1 2]


In [ ]:
# Készíts egy olyan függvényt, ami vissza adja string-ként a megadott array dimenzióit:
# Be: [[1,2,3], [4,5,6]]
# Ki: "sor: 2, oszlop: 3, melyseg: 1"
# get_array_shape()
# 3D-vel még műküdnie kell!, 

In [13]:
def get_array_shape(arr) -> str:
    try:
        melyseg=len(arr[0][0])

    except: 
        melyseg=1
    return f"sor: {len(arr)}, oszlop: {len(arr[0])}, melyseg: {melyseg}"
#print(get_array_shape([[1,2,3], [4,5,6]]))

sor: 2, oszlop: 3, melyseg: 1


In [21]:
def get_array_shape2(arr):
    dim = np.shape(arr)
    print(dim)
    d = np.array(arr).ndim
    print(d)
    return f"sor: {dim[0]}, oszlop: {dim[1] if d >1 else 1}, melyseg: {dim[2] if d > 2 else 1}"
print(get_array_shape2([[1,2,3], [4,5,6]]))

(2, 3)
2
sor: 2, oszlop: 3, melyseg: 1


In [ ]:
# Készíts egy olyan függvényt, aminek segítségével elő tudod állítani egy neurális hálózat tanításához szükséges pred-et egy numpy array-ből. 
# Bementként add meg az array-t, illetve hogy mennyi class-od van. Kimenetként pedig adjon vissza egy 2d array-t, ahol a sorok az egyes elemek. 
# Minden nullákkal teli legyen és csak ott álljon egyes, ahol a bementi tömb megjelöli. 
# Pl. ha 1 van a bemeneten és 4 classod van, akkor az adott sorban az array-ban a [1] helyen álljon egy 1-es, a többi helyen pedig 0.
# Be: [1, 2, 0, 3], 4
# Ki: [[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]]
# encode_Y()

In [75]:
def encode_Y(arr: np.array,cl : int) -> np.array:
    shape = np.array(arr).shape[0]
    pred =np.zeros((shape,cl),int)
    pred[np.arange(shape),arr]=1
    return pred
#print(encode_Y([1, 2, 0, 3], 4))

[[0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]]


In [ ]:
# A fenti feladatnak valósítsd meg a kiértékelését. Adj meg a 2d array-t és adj vissza a decodolt változatát
# Be:  [[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]]
# Ki:  [1, 2, 0, 3]
# decode_Y()

In [79]:
def decode_Y(pred : np.array) -> np.array:
    return np.argmax(pred,axis=1)
#print(decode_Y([[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]]))

[1 2 0 3]


In [ ]:
# Készíts egy olyan függvényt, ami képes kiértékelni egy neurális háló eredményét! 
# Bemenetként egy listát és egy array-t és adja vissza azt az elemet, aminek a legnagyobb a valószínüsége(értéke) a listából.
# Be: ['alma', 'körte', 'szilva'], [0.2, 0.2, 0.6]. # Az ['alma', 'körte', 'szilva'] egy lista!
# Ki: 'szilva'
# eval_classification()

In [80]:
def eval_classification(arr : np.array, lst : list) -> str:
    return arr[np.argmax(lst)]
#print(eval_classification(['alma', 'körte', 'szilva'], [0.2, 0.2, 0.6]))

szilva


In [ ]:
# Készíts egy olyan függvényt, ahol az 1D array-ben a páratlan számokat -1-re cseréli
# Be: [1,2,3,4,5,6]
# Ki: [-1,2,-1,4,-1,6]
# repalce_odd_numbers()

In [26]:
def replace_odd_numbers(arr : np.array)->np.array:
    arr=np.array(arr)
    return np.where(arr%2==1,-1,arr)
    #arr[arr % 2 == 1] = -1
    #return arr
#print(replace_odd_numbers([1,2,3,4,5,6]))

In [ ]:
# Készíts egy olyan függvényt, ami egy array értékeit -1 és 1-re változtatja, attól függően, hogy az adott elem nagyobb vagy kisebb a paraméterként megadott számnál.
# Ha a szám kisebb mint a megadott érték, akkor -1, ha nagyobb vagy egyenlő, akkor pedig 1.
# Be: [1, 2, 5, 0], 2
# Ki: [-1, 1, 1, -1]
# replace_by_value()

In [105]:
def replace_by_value(arr : np.array,num : int)->np.array:
    arr=np.array(arr)
    return np.where(arr>num,1,-1)
#print(replace_by_value([1, 2, 5, 0], 2))

In [ ]:
# Készíts egy olyan függvényt, ami egy array értékeit összeszorozza és az eredményt visszaadja
# Be: [1,2,3,4]
# Ki: 24
# array_multi()
# Ha több dimenziós a tömb, akkor az egész tömb elemeinek szorzatával térjen vissza

In [112]:
def array_multi(arr : np.array)->int:
    arr=np.array(arr,int)
    return np.prod(arr)
#print(array_multi([1,2,3,4]))

24


In [ ]:
# Készíts egy olyan függvényt, ami egy 2D array értékeit összeszorozza és egy olyan array-el tér vissza, aminek az elemei a soroknak a szorzata
# Be: [[1, 2], [3, 4]]
# Ki: [2, 12]
# array_multi_2d()

In [117]:
def array_multi_2d(arr : np.array)->np.array:
    return np.prod(arr,axis=1)
#print(array_multi_2d([[1, 2], [3, 4]]))

In [ ]:
# Készíts egy olyan függvényt, amit egy meglévő numpy array-hez készít egy bordert nullásokkal. Bementként egy array-t várjon és kimenetként egy array jelenjen meg aminek van border-je
# Be: [[1,2],[3,4]]
# Ki: [[0,0,0,0],[0,1,2,0],[0,3,4,0],[0,0,0,0]]
# add_border()


In [10]:
def add_border(arr : np.array) -> np.array:
    arr=np.array(arr)
    padded=np.zeros(np.array(arr.shape)+2)
    padded[1:-1,1:-1]=arr
    return padded
#print(add_border([[1,2],[3,4]]))

In [ ]:
# A KÖTVETKEZŐ FELADATOKHOZ NÉZZÉTEK MEG A NUMPY DATA TYPE-JÁT!

In [7]:
from datetime import datetime, timedelta, date

In [ ]:
# Készíts egy olyan függvényt ami két dátum között felsorolja az összes napot és ezt adja vissza egy numpy array-ben. A fgv ként str vár paraméterként 'YYYY-MM' formában.
# Be: '2023-03', '2023-04'  # mind a kettő paraméter str.
# Ki: ['2023-03-01', '2023-03-02', .. , '2023-03-31',]
# list_days()

In [9]:
def list_days(start_date:str, end_date:str)->np.array:
    start_date = datetime.strptime(start_date, '%Y-%m')
    end_date = datetime.strptime(end_date, '%Y-%m')
    
    delta = end_date - start_date
    days = [start_date + timedelta(days) for days in range(delta.days + 1)]
    
    days_str = [day.strftime('%Y-%m-%d') for day in days]
    
    return np.array(days_str)
#print(list_days('2023-03', '2023-04'))


In [8]:
def list_days2(start_date:str, end_date:str)->np.array:
  start_date = datetime.strptime(start_date, '%Y-%m')
  end_date = datetime.strptime(end_date, '%Y-%m')
  return np.arange(start_date,end_date,dtype = 'datetime64[D]')
print(list_days2('2023-03', '2023-04'))

['2023-03-01' '2023-03-02' '2023-03-03' '2023-03-04' '2023-03-05'
 '2023-03-06' '2023-03-07' '2023-03-08' '2023-03-09' '2023-03-10'
 '2023-03-11' '2023-03-12' '2023-03-13' '2023-03-14' '2023-03-15'
 '2023-03-16' '2023-03-17' '2023-03-18' '2023-03-19' '2023-03-20'
 '2023-03-21' '2023-03-22' '2023-03-23' '2023-03-24' '2023-03-25'
 '2023-03-26' '2023-03-27' '2023-03-28' '2023-03-29' '2023-03-30'
 '2023-03-31']


In [ ]:
# Írj egy függvényt ami vissza adja az aktuális dátumot az alábbi formában: YYYY-MM-DD. Térjen vissza egy 'numpy.datetime64' típussal.
# Be:
# Ki: 2017-03-24


In [3]:

import datetime as dt
from datetime import date
def datenow()->str:
    return date.today()
print(datenow())

2023-03-13


In [ ]:
# Írj egy olyan függvényt ami visszadja, hogy mennyi másodperc telt el 1970 január 01. 00:02:00 óta. Int-el térjen vissza
# Be: 
# Ki: másodpercben az idó, int-é kasztolva
# sec_from_1970()

In [32]:
def sec_from_1970()->int:
    a=np.datetime64('1970-01-01T00:02:00')
    now=np.datetime64('now')
    return (now-a).astype('timedelta64[s]').astype(int)
#print(sec_from_1970())